apiVersion: v1
kind: Namespace
metadata:
 name: actuator-sample

apiVersion: apps/v1
kind: Deployment
metadata:
  name: actuator-sample
  namespace: actuator-sample
spec:
  selector:
    matchLabels:
      type: api
      service: actuator-sample
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        type: api
        service: actuator-sample
    spec:
      containers:
      - name: actuator-sample
        image: docker.io/prasath/actuator-sample:<tag> 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-server

-----

apiVersion: v1
kind: Service
metadata:
  name: actuator-sample
spec:
  ports:
  - port: 80
    targetPort: http-server
  selector:
    type: api
    service: actuator-sample
  type: LoadBalancer